# Generated by Django 3.2.4 on 2021-06-21 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name'], 'permissions': (('can_modify_author', 'Add Update and Delete perm'),)},
        ),
    ]
